SKEY = {}
SKEY.HOTUPDATE_ENTRY = "updated_hotupdate_entry"
SKEY.UUID = "uuid"
SKEY.UIN = "__uin"
SKEY.OPEN_ID = "__openid"
SKEY.TOKEN = "___token"
SKEY.LOGIN_TYPE = "__login_type"
SKEY.MIGU_TOKEN = "migu_token"
SKEY.SDKACCOUNT_LOGIN = "USER_SDKACCOUNT_LOGIN"
SKEY.FIRST_GAME_FLAG = "_isFirstgame"
SKEY.ZIP_CURRENT_VERSION = "current-version-code"
SKEY.ZIP_DOWNLOAD_VERSION = "downloaded-version-code"
SKEY.RES_VERSION = "_resversion"
SKEY.BASE_VERSION = "_baseversion"
SKEY.NEW_FRIEND = "NEWFRIEND"
SKEY.CLOSE_DAY = "closeDay"
SKEY.DEALER_ID = "my_heguan_id"
SKEY.MENU_FLAG_DISABLED = "menu_record_flag_disabled"
SKEY.MENU_CREATE_TIME = "menu_create_time"
SKEY.JPUSH_TAG_1 = "jupsh_tag_1"
SKEY.JPUSH_TAG_2 = "jupsh_tag_2"
SKEY.JPUSH_TAG_3 = "jupsh_tag_3"
SKEY.JPUSH_TIME = "jpush_time_"
SKEY.LABA_SEND_NUM = "sendNum"
SKEY.ACTIVITY_NOTICE_TIMES = "active_notice_times"
SKEY.ACTIVITY_NOTICE_DAY = "active_notice_day"
SKEY.SETTINGS_MUSIC = "MUSIC"
SKEY.SETTINGS_EFFECT = "EFFECT"
SKEY.SETTINGS_SHOCK = "SHOCK"
SKEY.SEND_GIFT_TIP_CLOSE_TIME = "send_gift_close_time"
SKEY.VERIFY_CODE = "verify_code"
SKEY.DEFAULT_PAYMETHOD = "default_paymethod"
SKEY.GAME_INSTALL_LIST  = "game_list" --游戏列表
SKEY.REVIEW_STATUS  = "review_status" --游戏列表
SKEY.QUICKSTARTGAME  = "QUICKSTARTGAME" --大厅立即开始游戏选择

SKEY.ZJH_GIFTLEAD = "zjh_giftlead"--龙虎斗送礼引导
SKEY.LOGIN_TIP_POP = "login_tip_pop"--登录成功后的提示（包括每日登录，banner跳转等）

SKEY.FLASH_TIME = "flash_time"  --闪屏显示时间
SKEY.IS_FLASH = "is_flash" --是否显示闪屏
SKEY.FLASH_IMG = "flash_img"
SKEY.BURST_INTERACT = "burst_interact" --互动表情连发
